services:
- type: web
  name: blue-meili
  env: docker
  repo: https://github.com/bloohq/meilisearch-docker-render.git
  plan: standard
  disk:
    name: meili-data
    mountPath: /meili-data
    sizeGB: 25
  envVars:
  - key: MEILI_HTTP_ADDR
    value: 0.0.0.0:80
  - key: MEILI_MASTER_KEY
    generateValue: true
  - key: MEILI_DB_PATH
    value: /meili-data
  - key: MEILI_ENV
    value: development
